CREATE DATABASE IF NOT EXISTS user_service;
CREATE DATABASE IF NOT EXISTS customer_service;
CREATE DATABASE IF NOT EXISTS employee_service;
CREATE DATABASE IF NOT EXISTS movies_service;
CREATE DATABASE IF NOT EXISTS inventory_service;
CREATE DATABASE IF NOT EXISTS rentals_service;
